on:
  workflow_dispatch:
  pull_request:
permissions: { }
jobs:
  linux:
    strategy:
      fail-fast: false

      matrix:
        py:
          - 'cp38'
          - 'cp39'
          - 'cp310'
          - 'cp311'
          - 'cp312'
          - 'cp313'
          - 'cp313t'
          - 'cp314'
          - 'cp314t'
        arch:
          - 'aarch64'
          - 'x86_64'
        abi:
          - 'manylinux'
          - 'musllinux'
        image:
          - 'manylinux2014'
          - 'manylinux_2_28'
          - 'musllinux_1_1'
          - 'musllinux_1_2'
        include:
          # Drop CPython 3.8 & 3.13t on 2026-05-05
          # https://github.com/pypa/manylinux/issues/1882
          # so here's tha last image that supports cp38
          # https://quay.io/repository/pypa/manylinux2014_x86_64?tab=tags
          # but still use `latest` on musllinux_1_1
          - py: 'cp38'
            image: 'manylinux2014'
            image_tag: '2026.05.02-2'
          - py: 'cp38'
            image: 'musllinux_1_2'
            image_tag: '2026.05.02-2'
          - py: 'cp313t'
            image: 'manylinux2014'
            image_tag: '2026.05.02-2'
          - py: 'cp313t'
            image: 'manylinux_2_28'
            image_tag: '2026.05.02-2'
          - py: 'cp313t'
            image: 'musllinux_1_2'
            image_tag: '2026.05.02-2'
        exclude:
          # Cancel out abi - image mismatch.
          - abi: 'manylinux'
            image: 'musllinux_1_1'
          - abi: 'manylinux'
            image: 'musllinux_1_2'
          - abi: 'musllinux'
            image: 'manylinux2014'
          - abi: 'musllinux'
            image: 'manylinux_2_28'
          # Switch to manylinux_2_28 on 3.14+.
          - py: 'cp38'
            image: 'manylinux_2_28'
          - py: 'cp39'
            image: 'manylinux_2_28'
          - py: 'cp310'
            image: 'manylinux_2_28'
          - py: 'cp311'
            image: 'manylinux_2_28'
          - py: 'cp312'
            image: 'manylinux_2_28'
          - py: 'cp313'
            image: 'manylinux_2_28'
          - py: 'cp314'
            image: 'manylinux2014'
          - py: 'cp314t'
            image: 'manylinux2014'
          # Drop support for musllinux_1_1 on 3.14+
          - py: 'cp314'
            image: 'musllinux_1_1'
          - py: 'cp314t'
            image: 'musllinux_1_1'
    runs-on: ${{ matrix.arch == 'aarch64' && 'ubuntu-22.04-arm' || 'ubuntu-22.04' }}
    env:
      CIBW_ARCHS: ${{ matrix.arch }}
      CIBW_BUILD: ${{ matrix.py }}-${{ matrix.abi }}_${{ matrix.arch }}
      CIBW_BUILD_FRONTEND: 'build[uv]'
      CIBW_BUILD_VERBOSITY: '1'
      # Strip debug symbols from all ELF files so wheels stay small.
      CIBW_REPAIR_WHEEL_COMMAND: 'auditwheel repair --strip -w {dest_dir} {wheel}'
      CIBW_MANYLINUX_AARCH64_IMAGE: quay.io/pypa/${{ matrix.image }}_aarch64:${{ matrix.image_tag || 'latest' }}
      CIBW_MANYLINUX_X86_64_IMAGE: quay.io/pypa/${{ matrix.image }}_x86_64:${{ matrix.image_tag || 'latest' }}
      CIBW_MUSLLINUX_AARCH64_IMAGE: quay.io/pypa/${{ matrix.image }}_aarch64:${{ matrix.image_tag || 'latest' }}
      CIBW_MUSLLINUX_X86_64_IMAGE: quay.io/pypa/${{ matrix.image }}_x86_64:${{ matrix.image_tag || 'latest' }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@d9e0f98d3fc6adb07d1e3d37f3043649ddad06a1 # v6.5.0
        with:
          version: "0.8.11"

      - name: Build wheels
        run: |
          uvx -p 3.13 cibuildwheel@3.1.4

      - name: Upload Wheel
        if: ${{ !endsWith(matrix.py, 't') }}
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: linux-${{ matrix.py }}-${{ matrix.arch }}-${{ matrix.abi }}-${{ matrix.image }}
          path: ./wheelhouse/*.whl

  macos:
    strategy:
      fail-fast: false
      matrix:
        py:
          - 'cp38'
          - 'cp39'
          - 'cp310'
          - 'cp311'
          - 'cp312'
          - 'cp313'
          - 'cp313t'
          - 'cp314'
          - 'cp314t'
        arch:
          - 'arm64'
          - 'x86_64'
    runs-on: ${{ matrix.arch == 'x86_64' && 'macos-13' || 'macos-14' }}
    env:
      CIBW_ARCHES: ${{ matrix.arch }}
      CIBW_BUILD: ${{ matrix.py }}-macosx_${{ matrix.arch }}
      CIBW_BUILD_VERBOSITY: '1'
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@d9e0f98d3fc6adb07d1e3d37f3043649ddad06a1 # v6.5.0
        with:
          version: "0.8.11"

      - name: Build wheels
        run: |
          uvx -p 3.13 cibuildwheel@3.1.4

      - name: Upload Wheel
        if: ${{ !endsWith(matrix.py, 't') }}
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: macos-${{ matrix.py }}-${{ matrix.arch }}
          path: ./wheelhouse/*.whl

  windows:
    strategy:
      fail-fast: false
      matrix:
        py:
          - 'cp38'
          - 'cp39'
          - 'cp310'
          - 'cp311'
          - 'cp312'
          - 'cp313'
          - 'cp313t'
          - 'cp314'
          - 'cp314t'
        arch:
          - 'win_amd64'
          - 'win_arm64'
        exclude:
          - py: 'cp38'
            arch: 'win_arm64'
          - py: 'cp39'
            arch: 'win_arm64'
          - py: 'cp310'
            arch: 'win_arm64'
    runs-on: ${{ matrix.arch == 'win_arm64' && 'windows-11-arm' || 'windows-2022' }}
    env:
      CIBW_ARCHES: ${{ matrix.arch }}
      CIBW_BUILD: ${{ matrix.py }}-${{ matrix.arch }}
      CIBW_BUILD_VERBOSITY: '1'
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@d9e0f98d3fc6adb07d1e3d37f3043649ddad06a1 # v6.5.0
        with:
          version: "0.8.11"

      - name: Build wheels
        run: |
          uvx -p 3.13 cibuildwheel@3.1.4

      - name: Upload Wheel
        if: ${{ !endsWith(matrix.py, 't') }}
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: windows-${{ matrix.py }}-${{ matrix.arch }}
          path: ./wheelhouse/*.whl
